server.port: 7000
logging:
    level:
        root: debug
app:
    product-service:
        host: localhost
        port: 7001
    recommendation-service:
        host: localhost
        port: 7002
    review-service:
        host: localhost
        port: 7003
api:
    common:
        version: 1.0.0
        title: Hands On Microservices Book API
        description: Contains services described in the book Hands On Microservices with Spring Boot and Spring Cloud
        termsOfServiceUrl: https://policies.google.com/terms?hl=en-US
        license: Apache License, Version 2.0
        licenseUrl: https://www.apache.org/licenses/LICENSE-2.0
        contact:
            name: cirovladimir
            email: cirovladimir@gmail.com
            url: "https://twitter.com/cirovladimir"
    product-composite:
        get:
            description: Returns a composite view of the specified product id
            notes: |
                # Normal response
                If the requested product id is found the method will return information regarding:
                    - base product information
                    - reviews
                    - recommendations
                    - service adresses (technical information regarding the address of microservices that created the response)
                
                # Expected partial and error responses
                In the following cases, only a partial response will be created (used to simplify testing of error conditions)

                ## Product id 113
                200 - Ok, but no recommendations will be returned
                
                ## Product id 213
                200 - Ok, but no reviews will be returned
                
                ## Product id 13
                404 - A <b>Not found</b> error will be returned
                
                ## Non numerical product id 
                400 - A <b>Bad request</b> error will be returned
        create:
            description: Creates a composite product
            notes: |
                # Normal response
                The composite product information posted to the API will be splitted up
                and stored as separate product-info, recommendation and review entities.

                # Expected error responses
                1.- If a product with the same product id as specified in the posted information already exists, 
                an 442 - Unprocessable entity error with a duplicate key error message will be returned.
        delete:
            description: Deletes a product composite
            notes: |
                # Normal response
                Entities for product information, recommendation and reviews related to the specified productId will be deleted.