server.port: 7003
spring.jpa.hibernate.ddl-auto: update
spring.datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
spring.datasource.hikari.initializationFailTimeout: 60000
logging:
    level:
        root: info