server.port: 7003
spring.datasource:
    url: jdbc:mysql://localhost/review-db
    username: user
    password: pwd
spring.datasource.hikari.initializationFailTimeout: 60000
spring.jpa.hibernate.ddl-auto: update
logging:
    level:
        root: info
        org.hibernate.SQL: debug
        org.hibernate.type.descriptor.sql.BasicBinder: trace